### Importing Library

In [1]:
import numpy as np

### Array Creation

In [2]:
# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Using built-in NumPy methods
zeros = np.zeros((2, 3))
ones = np.ones((3, 3))
range_arr = np.arange(0, 10, 2)

print(arr_1d)
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### Indexing and Slicing

In [3]:
# Indexing
print(arr_1d[2])        # Access element
print(arr_2d[1, 2])     # Row 1, Column 2

# Slicing
print(arr_1d[1:4])
print(arr_2d[:, 1])     # All rows, column 1

3
6
[2 3 4]
[2 5]


### Mathematical Operations

In [5]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)
print(a * b)
print(a ** 2)

[11 22 33]
[10 40 90]
[100 400 900]


### Axis-wise Operations

In [6]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Axis 0 → column-wise
print("Column sum:", np.sum(matrix, axis=0))

# Axis 1 → row-wise
print("Row sum:", np.sum(matrix, axis=1))

Column sum: [5 7 9]
Row sum: [ 6 15]


### Statistical Operations

In [17]:
data = np.array([12, 15, 20, 22, 18, 30])

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print(f"Standard Deviation: {np.std(data):.2f}")
print("Min:", np.min(data))
print("Max:", np.max(data))

Mean: 19.5
Median: 19.0
Standard Deviation: 5.71
Min: 12
Max: 30


### Reshaping

In [11]:
arr = np.arange(1, 13)

reshaped = arr.reshape(3, 4)
print(reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Broadcasting

In [12]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

vector = np.array([10, 20, 30])

result = matrix + vector
print(result)

[[11 22 33]
 [14 25 36]]


### Save & Load NumPy Arrays

In [13]:
# Save array
np.save("sample_array.npy", matrix)

# Load array
loaded_array = np.load("sample_array.npy")
print(loaded_array)

[[1 2 3]
 [4 5 6]]


### NumPy vs Python List Performance

In [16]:
import time

# Python list
list_data = list(range(1_000_000))
start = time.time()
list_result = [x * 2 for x in list_data]
print("List time:", time.time() - start)

# NumPy array
np_data = np.array(list_data)
start = time.time()
np_result = np_data * 2
print("NumPy time:", time.time() - start)

List time: 0.2360239028930664
NumPy time: 0.0037615299224853516
